export const data = [
  {
    id: 1,
    firstName: "Terry",
    role: "admin",
    email: "atuny0@sohu.com",
    phone: "+63 791 675 8914",
    active: true,
  },
  {
    id: 2,
    firstName: "Sheldon",
    role: "user",
    email: "hbingley1@plala.or.jp",
    phone: "+7 813 117 7139",
    active: false,
  },
  {
    id: 3,
    firstName: "Terrill",
    role: "user",
    email: "rshawe2@51.la",
    phone: "+63 739 292 7942",
    active: true,
  },
  {
    id: 4,
    firstName: "Miles",
    role: "user",
    email: "yraigatt3@nature.com",
    phone: "+86 461 145 4186",
    active: true,
  },
  {
    id: 5,
    firstName: "Mavis",
    role: "user",
    email: "kmeus4@upenn.edu",
    phone: "+372 285 771 1911",
    active: false,
  },
  {
    id: 6,
    firstName: "Alison",
    role: "user",
    email: "jtreleven5@nhs.uk",
    phone: "+351 527 735 3642",
    active: true,
  },
  {
    id: 7,
    firstName: "Oleta",
    role: "user",
    email: "dpettegre6@columbia.edu",
    phone: "+62 640 802 7111",
    active: false,
  },
  {
    id: 8,
    firstName: "Ewell",
    role: "user",
    email: "ggude7@chron.com",
    phone: "+86 946 297 2275",
    active: true,
  },
  {
    id: 9,
    firstName: "Demetrius",
    role: "user",
    email: "nloiterton8@aol.com",
    phone: "+86 356 590 9727",
    active: true,
  },
  {
    id: 10,
    firstName: "Eleanora",
    role: "user",
    email: "umcgourty9@jalbum.net",
    phone: "+60 184 408 0824",
    active: true,
  },
  {
    id: 11,
    firstName: "Marcel",
    role: "user",
    email: "acharlota@liveinternet.ru",
    phone: "+967 253 210 0344",
    active: true,
  },
  {
    id: 12,
    firstName: "Assunta",
    role: "user",
    email: "rhallawellb@dropbox.com",
    phone: "+380 962 542 6549",
    active: false,
  },
  {
    id: 13,
    firstName: "Trace",
    role: "user",
    email: "lgribbinc@posterous.com",
    phone: "+1 609 937 3468",
    active: false,
  },
  {
    id: 14,
    firstName: "Enoch",
    role: "user",
    email: "mturleyd@tumblr.com",
    phone: "+94 912 100 5118",
    active: false,
  },
  {
    id: 15,
    firstName: "Jeanne",
    role: "user",
    email: "kminchelle@qq.com",
    phone: "+86 581 108 7855",
    active: true,
  },
  {
    id: 16,
    firstName: "Trycia",
    role: "user",
    email: "dpierrof@vimeo.com",
    phone: "+420 833 708 0340",
    active: true,
  },
  {
    id: 17,
    firstName: "Bradford",
    role: "user",
    email: "vcholdcroftg@ucoz.com",
    phone: "+420 874 628 3710",
    active: true,
  },
  {
    id: 18,
    firstName: "Arely",
    role: "user",
    email: "sberminghamh@chron.com",
    phone: "+55 886 766 8617",
    active: false,
  },
  {
    id: 19,
    firstName: "Gust",
    role: "user",
    email: "gusty@gmail.com",
    phone: "+86 886 889 0258",
    active: true,
  },
  {
    id: 20,
    firstName: "Lenna",
    role: "user",
    email: "aeatockj@psu.edu",
    phone: "+1 904 601 7177",
    active: true,
  },
  {
    id: 21,
    firstName: "Doyle",
    role: "user",
    email: "ckensleyk@pen.io",
    phone: "+86 634 419 6839",
    active: true,
  },
  {
    id: 22,
    firstName: "Tressa",
    role: "user",
    email: "froachel@howstuffworks.com",
    phone: "+34 517 104 6248",
    active: false,
  },
  {
    id: 23,
    firstName: "Felicity",
    role: "user",
    email: "beykelhofm@wikispaces.com",
    phone: "+63 919 564 1690",
    active: true,
  },
  {
    id: 24,
    firstName: "Jocelyn",
    role: "user",
    email: "brickeardn@fema.gov",
    phone: "+7 968 462 1292",
    active: true,
  },
  {
    id: 25,
    firstName: "Edwina",
    role: "user",
    email: "dfundello@amazon.co.jp",
    phone: "+86 376 986 8945",
    active: false,
  },
  {
    id: 26,
    firstName: "Griffin",
    role: "user",
    email: "lgronaverp@cornell.edu",
    phone: "+62 511 790 0161",
    active: true,
  },
  {
    id: 27,
    firstName: "Piper",
    role: "user",
    email: "fokillq@amazon.co.jp",
    phone: "+60 785 960 7918",
    active:true,
  },
  {
    id: 28,
    firstName: "Kody",
    role: "user",
    email: "xisherwoodr@ask.com",
    phone: "+81 859 545 8951",
    active: true,
  },
  {
    id: 29,
    firstName: "Macy",
    role: "user",
    email: "jissetts@hostgator.com",
    phone: "+81 915 649 2384",
    active: false,
  },
  {
    id: 30,
    firstName: "Maurine",
    role: "user",
    email: "kdulyt@umich.edu",
    phone: "+48 143 590 6847",
    active: false,
  },
];
